### PR TITLE
Added more language and fix some names

### PR DESCRIPTION
**Pull request by AntimatterReactor**
Added:

- batch
- brainfuck

### CODE REVIEW

**Comment by firefish111** [comment]
~~nobody uses batch, windows is bad~~ cool

**Comment by AntimatterReactor** [comment]
> ~nobody uses batch, windows is bad~ cool

bruh

**Comment by firefish111** [comment]
## linux good windows bad

**Review by R4356th — APPROVED** [review]
Thank you very much for your contribution!

**Comment by AntimatterReactor** [comment]
> ## linux good windows bad

(everyone knows that, dont tell anyone)

**Pull request merged**
